### ISSUE TITLE
haproxy_ssl_verify type mismatch

### ISSUE THREAD

**Issue by wosc** [evilmartians/chef-prometheus-exporters#23]
The haproxy resource declares [ssl_verify as `string`](https://github.com/evilmartians/chef-prometheus-exporters/blob/master/resources/haproxy.rb#L17), but it probably should be bool -- it currently at least clashes with [the default attribute value of `false`](https://github.com/evilmartians/chef-prometheus-exporters/blob/master/attributes/haproxy.rb#L7).

**Comment by dragonsmith** [comment]
@wosc Thanks a lot for the PR. Merged it.
