### ISSUE TITLE
RabbitMQ exporter doesn't load configuration from config file

### ISSUE THREAD

**Issue by liortzur-fiverr** [evilmartians/chef-prometheus-exporters#41]
RabbitMQ exporter seem to have a bug makes it be unable to load configuration when use a json config file.
It makes the rabbitmq resource install the exporter only with default configuration without an option to change it.
Until it would be fix I suggest to revert to the way I used at the first place, by loading configs within the execution command.
Example:
Config file created in /etc/rabbitmq_exporter_main.json:
```
{"max_queues":0,"output_format":"TTY","publish_addr":"127.0.0.1","publish_port":9419,"rabbit_capabilities":"nobert","enabled_exporters":["exchange","node","overview","queue"],"timeout":30,"rabbit_url":"http://127.0.0.1:15672","insecure_skip_verify":false}
```

Actual configuration loaded by the exporter:
```
BRANCH=heads/v1.0.0-RC6.1 BUILD_DATE="20190426-18:57:58" REVISION=6db8c3822c77b6577b39e6d5a1868c6c5a28dfe2 VERSION=1.0.0-RC6.1
INFO[0000] Active Configuration
CAFILE=ca.pem EXCLUDE_METRICS="[]" INCLUDE_QUEUES=".*" INCLUDE_VHOST=".*" MAX_QUEUES=0 OUTPUT_FORMAT=TTY PUBLISH_ADDR= PUBLISH_PORT=9419 RABBIT_CAPABILITIES="bert,no_sort" RABBIT_EXPORTERS="[exchange node overview queue]" RABBIT_TIMEOUT=30 RABBIT_URL="http://127.0.0.1:15672" RABBIT_USER=guest SKIPVERIFY=false SKIP_QUEUES="^$" SKIP_VHOST="^$"
```

Note the setting of rabbit_capabilities wasn't loaded by the rabbitmq exporter.

**Comment by dragonsmith** [comment]
@liortzur-fiverr do you have any good ideas on how to better test for this bug to check whether it is still there?

**Comment by liortzur-fiverr** [comment]
@dragonsmith the rabbit exporter writes to log the configs it loaded. It is possible to compare the configs given by the cookbook to those which actually loaded.

**Comment by dragonsmith** [comment]
Uh, ok.

I've released the new version. I've removed the wrapper script. Cannot explain in details but I kinda dislike that solution, but I've used your new PR as a reference heavily. Thank you very much!

**Comment by dragonsmith** [comment]
@liortzur-fiverr please confirm everithing works ok for you. I'll close this issue after that.

**Comment by liortzur-fiverr** [comment]
Thank you @dragonsmith! 
It works well.
