### ISSUE TITLE
error with chef 13

### ISSUE THREAD

**Issue by Grummfy** [evilmartians/chef-prometheus-exporters#7]
Hello,
I use chef solo (13.8.5) and when I use the resource from this package, i got error

>   * node_exporter[main] action enable
> 
>     ================================================================================
>     Error executing action `enable` on resource 'node_exporter[main]'
>     ================================================================================
> 
>     NoMethodError
>     -------------
>     undefined method `map' for nil:NilClass
> 
>     Cookbook Trace:
>     ---------------
>     /root/chef-solo/local-mode-cache/cache/cookbooks/prometheus_exporters/resources/node.rb:110:in `block in class_from_file'
>     /root/chef-solo/local-mode-cache/cache/cookbooks/prometheus_exporters/resources/node.rb:224:in `block in class_from_file'

**Comment by emourant** [comment]
I can confirm this is also happening on chef 12. I was able to work around this by adding `collectors_enabled` and `collectors_disabled` options to my `node_exporter` block

for example, this seems to do the trick:
```
node_exporter "main" do
  collectors_enabled node['prometheus_exporters']['node']['collectors_enabled']
  collectors_disabled []
  web_listen_address "0.0.0.0:9100"
  action [:enable, :start]
end
```

**Comment by dragonsmith** [comment]
@Grummfy, @emourant thank you for your feedback!

I'll see what can be fixed today.
